name: Publish to Cocoapods

on:
  workflow_dispatch:

jobs:
  pod_publish:
    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: Install Cocoapods
      run: gem install cocoapods
    - name: Deploy
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
